# Generated by Django 5.2.12 on 2026-05-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GymMemberDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField()),
                ('plan', models.CharField(max_length=20)),
                ('duration', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('final_billing', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
